spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/MOOC_content?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-content
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

server:
  port: 8000

mybatis-plus:
  type-aliases-package: edu.wust.qrz.entity.content


