spring:
  datasource:
    url: jdbc:mysql://8.153.171.104:3306/MOOC_content?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: QRZ15671737720
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-content
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

server:
  port: 8000


