spring:
  cloud:
    gateway:
      routes:
        - id: service-content
          uri: lb://service-content
          predicates:
            - Path=/api/services/content/**
          filters:
            - RewritePath=/api/services/content/?(?<segment>.*), /$\{segment}

        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/api/services/system/**
          filters:
            - RewritePath=/api/services/system/?(?<segment>.*), /$\{segment}

        - id: service-media
          uri: lb://service-media
          predicates:
            - Path=/api/services/media/**
          filters:
            - RewritePath=/api/services/media/?(?<segment>.*), /$\{segment}