spring:
  cloud:
    gateway:
      routes:
        - id: service-content
          uri: lb://service-content
          predicates:
            - Path=/api/services/content/**
          filters:
            - RewritePath=/api/services/content/?(?<segment>.*), /$\{segment}