spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
            '[/**]':
              allowedOrigins:
                - "http://127.0.0.1:5500"
                - "http://localhost:5500"
              allowedMethods:
                - GET
                - POST
                - OPTIONS
              allowedHeaders:
                  - "*"