spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/MOOC_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-system
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

server:
  port: 8001